# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty


# Setup
title:               Charles K Lam
tagline:             'Chucklin'' at Life and Blogging about it'
description:         'Engineer, Developer, Student, Dreamer'
url:                 "http://chucklinatlife.github.io/blog"
baseurl:             '/blog'
paginate:            5

#to change
# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0
